// Generates app/zh-hant.ts — a Simplified→Traditional table covering exactly the
// vocabulary this site uses. Run after editing any user-visible Chinese text:
//
//     node scripts/build-zh-hant.mjs
//
// Shipping OpenCC itself would add ~6 MB of dictionaries for a font toggle, so
// the conversion happens here and only the resulting table reaches the browser.
import { readFileSync, writeFileSync } from 'node:fs';
import * as OpenCC from 'opencc-js';

const SOURCES = ['app/page.tsx', 'app/places.ts', 'app/geo.ts', 'app/videos.ts', 'app/jerusalem-map.tsx', 'app/jerusalem-data.ts'];

// OpenCC has no context beyond its phrase dictionary, and a few of our terms
// have a preferred Taiwanese form it does not pick. Tune here, nowhere else.
const OVERRIDES = {
  发掘: '發掘',
  受难周: '受難週',
  最后一周: '最後一週',
  一周: '一週',
  // OpenCC matches 海干 as a phrase and reads this as 沿海乾道.
  沿海干道: '沿海幹道',
};

const convert = OpenCC.Converter({ from: 'cn', to: 'tw' });

const text = SOURCES.map((f) => readFileSync(new URL(`../${f}`, import.meta.url), 'utf8')).join('\n');
const runs = [...new Set(text.match(/[一-鿿]+/g) ?? [])];

// Convert each run whole, so every character is resolved with its real context.
const converted = runs.map((run) => {
  let t = convert(run);
  // Apply vocabulary overrides before building longer context windows.
  for (const [k, v] of Object.entries(OVERRIDES)) {
    for (let i = run.indexOf(k); i !== -1; i = run.indexOf(k, i + 1)) {
      t = t.slice(0, i) + v + t.slice(i + k.length);
    }
  }
  if (t.length !== run.length) throw new Error(`conversion changed length: ${run} -> ${t}`);
  return t;
});

// Character table: for an ambiguous character (里 → 里 or 裡, 干 → 干 or 幹) take
// whichever form this site's own text uses most. The phrase table then only has
// to carry the minority readings.
const tally = new Map();
runs.forEach((run, r) => {
  for (let i = 0; i < run.length; i++) {
    const counts = tally.get(run[i]) ?? new Map();
    counts.set(converted[r][i], (counts.get(converted[r][i]) ?? 0) + 1);
    tally.set(run[i], counts);
  }
});
const chars = {};
for (const [ch, counts] of tally) {
  const [best] = [...counts].sort((a, b) => b[1] - a[1]);
  if (best[0] !== ch) chars[ch] = best[0];
}

const charwise = (s) => [...s].map((c) => chars[c] ?? c).join('');

// Phrase table: wherever the character table disagrees with the full-context
// conversion, keep a short window around the disagreement. The value always
// comes from the whole-run conversion, never from converting the fragment —
// OpenCC reads "沿海干" out of context as 沿海乾 rather than 沿海幹道.
const phrases = new Map();
const CONTEXT = 2;
runs.forEach((run, r) => {
  const naive = charwise(run);
  for (let i = 0; i < run.length; i++) {
    if (naive[i] === converted[r][i]) continue;
    const from = Math.max(0, i - CONTEXT);
    const to = Math.min(run.length, i + CONTEXT + 1);
    phrases.set(run.slice(from, to), converted[r].slice(from, to));
  }
});
for (const [k, v] of Object.entries(OVERRIDES)) phrases.set(k, v);

// Longest first, so the runtime scanner can take the first match it finds.
// Byte order, not locale order — CI must produce the same file this machine does.
const sorted = [...phrases].sort((a, b) => b[0].length - a[0].length || (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
const maxPhrase = Math.max(2, ...sorted.map(([k]) => k.length));

// The shipped table must reproduce OpenCC exactly over this site's vocabulary.
// A window taken out of context, or a character whose majority form is wrong,
// shows up here rather than in the browser.
const applyOverrides = (simplified, traditional) => {
  let out = traditional;
  for (const [k, v] of Object.entries(OVERRIDES)) {
    if (k.length !== v.length) throw new Error(`override must not change length: ${k} -> ${v}`);
    for (let i = simplified.indexOf(k); i !== -1; i = simplified.indexOf(k, i + 1)) {
      out = out.slice(0, i) + v + out.slice(i + k.length);
    }
  }
  return out;
};
const lookup = Object.fromEntries(sorted);
const reproduce = (input) => {
  let out = '';
  for (let i = 0; i < input.length; ) {
    let matched = false;
    for (let len = Math.min(maxPhrase, input.length - i); len >= 2; len--) {
      const hit = lookup[input.slice(i, i + len)];
      if (hit !== undefined) { out += hit; i += len; matched = true; break; }
    }
    if (matched) continue;
    out += chars[input[i]] ?? input[i];
    i += 1;
  }
  return out;
};
runs.forEach((run, r) => {
  const expected = applyOverrides(run, converted[r]);
  const actual = reproduce(run);
  if (actual !== expected) {
    throw new Error(`table does not reproduce OpenCC:\n  ${run}\n  got      ${actual}\n  expected ${expected}`);
  }
});

const out = `// AUTO-GENERATED by scripts/build-zh-hant.mjs — do not edit by hand.
// Simplified→Traditional (Taiwan) table for this site's vocabulary only,
// derived from OpenCC. Regenerate after changing any Chinese text.

const chars: Record<string, string> = ${JSON.stringify(chars)};

/** Only the sequences OpenCC renders differently than character substitution. */
const phrases: Record<string, string> = ${JSON.stringify(Object.fromEntries(sorted))};

const MAX_PHRASE = ${maxPhrase};

/** Greedy longest-match conversion. Text with no Chinese in it passes through. */
export function toTraditional(input: string): string {
  let out = '';
  for (let i = 0; i < input.length; ) {
    let matched = false;
    for (let len = Math.min(MAX_PHRASE, input.length - i); len >= 2; len--) {
      const hit = phrases[input.slice(i, i + len)];
      if (hit !== undefined) {
        out += hit;
        i += len;
        matched = true;
        break;
      }
    }
    if (matched) continue;
    const ch = input[i];
    out += chars[ch] ?? ch;
    i += 1;
  }
  return out;
}
`;
writeFileSync(new URL('../app/zh-hant.ts', import.meta.url), out);
console.log(`ok — ${Object.keys(chars).length} characters, ${sorted.length} phrases`);
console.log(sorted.map(([k, v]) => `${k}→${v}`).join('  '));
